version: "3.9"

services:
  backend:
    build:
      context: ./fitfusion-backend
    ports:
      - "3000:3000"
    env_file:
      - ./fitfusion-backend/.env
    volumes:
      - ./fitfusion-backend:/app
    restart: always

  frontend:
    build:
      context: ./fitfusion-frontend
    ports:
      - "5173:80"
    volumes:
      - ./fitfusion-frontend:/app
    restart: always
