# File: .github/workflows/frontend-ci.yml

name: Frontend CI

on:
  push:
    paths:
      - 'fitfusion-frontend/**'
  pull_request:
    paths:
      - 'fitfusion-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./fitfusion-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies (with legacy peer deps)
        run: npm install --legacy-peer-deps

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
