name: Frontend CI

on:
  push:
    paths:
      - 'fitfusion-frontend/**'
  pull_request:
    paths:
      - 'fitfusion-frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Clean existing node_modules and lockfile
        run: |
          rm -rf node_modules package-lock.json
        working-directory: ./fitfusion-frontend

      - name: Install dependencies (force peer deps resolution)
        run: npm install --legacy-peer-deps
        working-directory: ./fitfusion-frontend

      - name: Run lint
        run: npm run lint
        working-directory: ./fitfusion-frontend

      - name: Run tests
        run: npm test
        working-directory: ./fitfusion-frontend

      - name: Build app
        run: npm run build
        working-directory: ./fitfusion-frontend
